.TH "D:/Workspace/C++/textanal/source/computation.cpp" 3 "Wed Jan 19 2022" "Version .3" "Text Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/C++/textanal/source/computation.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'computation\&.h'\fP
.br
\fC#include 'statistics\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprocessText\fP (std::vector< std::string >bookVec, int numOfThread)"
.br
.RI ": This is the 'main function' creates all the other threads based on the number given "
.ti -1c
.RI "std::string \fBcleanup\fP (std::string inWord)"
.br
.RI "just a garbage cleanup method that removes punctuation and other stuff from the word "
.ti -1c
.RI "void * \fBtask\fP (void *rec_struct)"
.br
.RI "The brains behind the application: Iterates through its subsection of book depending on #threads, And from there it itemizes each element in the book into a map\&. "
.ti -1c
.RI "std::string \fBremoveChar\fP (std::string str, char bad)"
.br
.RI "Function to remove all occurrences of a char from the string\&. "
.ti -1c
.RI "void \fBoutputReport\fP (std::map< std::string, int > wordM)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::mutex \fBfreqMtx\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string cleanup (std::string inWord)"

.PP
just a garbage cleanup method that removes punctuation and other stuff from the word 
.PP
\fBParameters\fP
.RS 4
\fIinWord\fP is a string we want to clean up 
.RE
.PP
\fBReturns\fP
.RS 4
The modified stream 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBcomputation\&.cpp\fP\&.
.SS "void outputReport (std::map< std::string, int > wordM)"

.PP
Definition at line \fB101\fP of file \fBcomputation\&.cpp\fP\&.
.SS "void processText (std::vector< std::string > bookVec, int numOfThread)"

.PP
: This is the 'main function' creates all the other threads based on the number given 
.PP
\fBParameters\fP
.RS 4
\fI\fP The book saved as a vector of strings, numThread is the number of threads to be created 
.RE
.PP

.PP
Definition at line \fB12\fP of file \fBcomputation\&.cpp\fP\&.
.SS "std::string removeChar (std::string str, char bad)"

.PP
Function to remove all occurrences of a char from the string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP This is the string we are modifying 
.br
\fIbad\fP is the character we would like the remove 
.RE
.PP
\fBReturns\fP
.RS 4
the Modified string 
.RE
.PP

.PP
Definition at line \fB96\fP of file \fBcomputation\&.cpp\fP\&.
.SS "void * task (void * threadid)"

.PP
The brains behind the application: Iterates through its subsection of book depending on #threads, And from there it itemizes each element in the book into a map\&. 
.PP
\fBParameters\fP
.RS 4
\fIthreadid\fP This is the \fBinputStruct\fP above it contains index of thread, numofthreads that exist and the book 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB54\fP of file \fBcomputation\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "std::mutex freqMtx"

.PP
Definition at line \fB10\fP of file \fBcomputation\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Text Analysis from the source code\&.
