.TH "D:/Workspace/C++/textanal/source/filep.h" 3 "Wed Jan 19 2022" "Version .3" "Text Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/C++/textanal/source/filep.h
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBinputloc\fP   '\&.\&./inputs/'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBstringConc\fP (const char *filename)"
.br
.ti -1c
.RI "std::vector< std::string > \fBprocessFil\fP (const char *argv)"
.br
.RI ": We open and read the File "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define inputloc   '\&.\&./inputs/'"

.PP
Definition at line \fB8\fP of file \fBfilep\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "std::vector< std::string > processFil (const char * argv)"

.PP
: We open and read the File 
.PP
\fBParameters\fP
.RS 4
\fI\fP The File name argument we recieved from CLI 
.RE
.PP
\fBReturns\fP
.RS 4
: Nothing 
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBfilep\&.cpp\fP\&.
.SS "std::string stringConc (const char * filename)"

.PP
\fBParameters\fP
.RS 4
\fI\fP filename is the file name(must be in inputs folder! 
.RE
.PP
\fBReturns\fP
.RS 4
: Returns a string of file name 
.RE
.PP

.PP
Definition at line \fB7\fP of file \fBfilep\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Text Analysis from the source code\&.
