.TH "inputStruct" 3 "Wed Jan 19 2022" "Version .3" "Text Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <computation\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.ti -1c
.RI "unsigned int \fBnumOfThread\fP"
.br
.ti -1c
.RI "std::vector< std::string > * \fBbookP\fP"
.br
.ti -1c
.RI "std::map< std::string, int > * \fBwordMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBcomputation\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string>* inputStruct::bookP"

.PP
Definition at line \fB25\fP of file \fBcomputation\&.h\fP\&.
.SS "unsigned int inputStruct::index"

.PP
Definition at line \fB24\fP of file \fBcomputation\&.h\fP\&.
.SS "unsigned int inputStruct::numOfThread"

.PP
Definition at line \fB24\fP of file \fBcomputation\&.h\fP\&.
.SS "std::map<std::string,int>* inputStruct::wordMap"

.PP
Definition at line \fB27\fP of file \fBcomputation\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Text Analysis from the source code\&.
