.TH "D:/Workspace/C++/textanal/source/main.cpp" 3 "Wed Jan 19 2022" "Version .3" "Text Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Workspace/C++/textanal/source/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'filep\&.h'\fP
.br
\fC#include 'computation\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBnumThread\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define numThread   4"

.PP
Definition at line \fB11\fP of file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB14\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Text Analysis from the source code\&.
