name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    #After Checked out
    - name: Run a one-line script
      run: echo Branch is Checked Out!
      
    - name: Running cmake (windows)
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
    #MSBuild.exe CMakeHelloWorld.sln
    - name: Build Solution (windows)
      run: |
        cd build

    - name: Clean Up
      run: |
        rm build
